server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 1234
mybatis:
  type-aliases-package: com.xiaogang.mybatisspringbootdemo.model
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true